apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitops-demo-prod
resources:
  - ../../base
patches:
  - path: patch-env.yaml
images:
  - name: lifecycle-quest
    newName: image-registry.openshift-image-registry.svc:5000/gitops-demo-dev/lifecycle-quest
    newTag: bootstrap
commonLabels:
  app.kubernetes.io/instance: lifecycle-quest-prod
  app.kubernetes.io/environment: prod
