apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lifecycle-quest-project.yaml
  - lifecycle-quest-platform.yaml
  - lifecycle-quest-dev.yaml
  - lifecycle-quest-test.yaml
  - lifecycle-quest-prod.yaml
