apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifecycle-quest
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: web
          env:
            - name: APP_ENV
              value: dev
            - name: APP_VERSION
              value: bootstrap
            - name: MESSAGE
              value: "Development stage: build fast, learn faster!"
